# Generated by Django 3.2.8 on 2021-11-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('numberOfHouse', models.IntegerField(max_length=5)),
                ('postCode', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=6)),
            ],
        ),
    ]
