# Generated by Django 3.2.8 on 2021-11-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_counter',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
