# Generated by Django 3.2.8 on 2021-11-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_buy_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buy_counter',
            field=models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=6),
        ),
    ]
