# Generated by Django 3.2.8 on 2021-11-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_person_numberofhouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Numbers',
            field=models.CharField(default='Siema', max_length=14),
        ),
    ]
