# Generated by Django 3.2.9 on 2021-11-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.DecimalField(decimal_places=0, default=3, max_digits=2),
        ),
    ]
