# Generated by Django 3.2.9 on 2021-11-30 20:08

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
