# Generated by Django 3.2.8 on 2021-11-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_person_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Numbers',
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
