# Generated by Django 3.2.9 on 2021-12-02 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_basket'),
        ('main', '0005_alter_product_description'),
    ]

    operations = [
    ]
