# Generated by Django 3.2.9 on 2021-12-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211204_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='stars',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
