# Generated by Django 3.2.9 on 2021-12-05 09:27

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
