# Generated by Django 3.2.9 on 2021-12-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20211205_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='product',
            field=models.ManyToManyField(default=None, related_name='profiles', to='main.Product'),
        ),
    ]
