# Generated by Django 3.2.9 on 2021-12-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_basket_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='product',
        ),
    ]
