# Generated by Django 3.2.9 on 2021-12-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_basket_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='product',
            field=models.ManyToManyField(to='main.Product'),
        ),
    ]
