# Generated by Django 3.2.9 on 2021-12-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_addcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='basket',
            name='user',
        ),
    ]
